***First Task***

In [45]:
#use intersect1d to finds the distinct/unique common items between two arrays a and b#
import numpy as np 
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a,b)

array([2, 4])

***Second Task***

In [9]:
#use arange to get 0-15, then use [1:] to get array from 1 to 15, then function T to reshape 5X3 array to 3X5#
import numpy as np 
a = np.arange(16)[1:].reshape((3,5)).T
print(a)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]



***Third Task***

In [6]:
#use setdiff1d function to remove from array a any items that are also present in array b.
import numpy as np
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
a = np.setdiff1d(a,b)
print(a)

[ 1  7  8 15]


***Fourth Task***

In [22]:
#The distance between NYC to Key West is 1550 miles, so I manually create array that cumulate the distance everyday
import numpy as np
miles = [55, 100, 150, 190, 240,300,300,350,400,400,440,480,530,600,650,710,760,800,850,890,920,960,
                    1010,1050,1100,1140,1200,1200,1280,1340,1400,1400,1450,1500,1550]
totaldistance = np.array(miles)
totaldistance

array([  55,  100,  150,  190,  240,  300,  300,  350,  400,  400,  440,
        480,  530,  600,  650,  710,  760,  800,  850,  890,  920,  960,
       1010, 1050, 1100, 1140, 1200, 1200, 1280, 1340, 1400, 1400, 1450,
       1500, 1550])

In [27]:
milesperday = np.diff(totaldistance) #np.diff function to show the milesperday
print(milesperday)

[45 50 40 50 60  0 50 50  0 40 40 50 70 50 60 50 40 50 40 30 40 50 40 50
 40 60  0 80 60 60  0 50 50 50]


***Write up***
###First, I Google the distance between NYC and Key West by bike, then it shows 1550 miles. I manually create the sum of 
distance every day, so the miles list is cumulative miles day by day. Finally, I use the Numpy function which is np.array to show all the data from the list. The array shows cumulative mileages day by day and it is easily to see some numbers are same because of eitherweather condition or personal fatigue, there are 4 days that the cumulative mileages are the same. In addtion, I use the np.diff function to show each day mileage from day 1 to day 35. Same as the cumulative mileages show above, the milesperday is easier to see that there are 4 days that milesperday is 0 which means that these 4 days are not driving.###

***Last***

In [8]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

C:\Users\renzhu\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

In [28]:
# The first question about maximum yearly NYC consumption of water in millions of gallons per day, I use np.max function.
nycconsumption = np.max(nyc_water[:,2])
print(nycconsumption)

1512.0


In [29]:
# the second question about how many calendar years are represented within this data set? I use np.size function
years = np.size(nyc_water,axis=0)
print(years)

39


In [30]:
# the third question is about what is the mean and the standard deviation of the per capita daily water consumption,
# I use mean and std function to show the answer
mean_per_capita=np.mean(nyc_water[:,3])
standard_per_capita=np.std(nyc_water[:,3])
print(mean_per_capita)
print(standard_per_capita)

160.30769230769232
31.51894330370624


In [35]:
#The final question is about what is the increase or decrease in population from year to year, np.diff Numpy function is good
#solution for this question
pop_diff = np.diff(nyc_water[:,1])
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
